import type { Application, ArchitectureDiagram, Incident } from "@secureflow/types";

import { now } from "./clock";
const hours = (n: number) => new Date(now - n * 3_600_000).toISOString();

export const applications: Application[] = [
  {
    id: "app-payments",
    name: "Payments API",
    slug: "payments-api",
    description: "Core payment initiation and settlement API serving mobile and partner channels.",
    ownerUserId: "u-rowan",
    teamId: "team-payments",
    repositoryId: "repo-payments",
    technology: ["TypeScript", "Fastify", "PostgreSQL", "AKS"],
    cloudEnvironment: "Azure — AKS (private cluster)",
    currentVersion: "v2.14.3",
    deploymentStatus: "healthy",
    pipelineHealth: "healthy",
    securityScore: 84,
    complianceScore: 91,
    lastDeploymentAt: hours(7),
    openVulnerabilities: { critical: 1, high: 2, medium: 5, low: 9 },
    availability: "99.97%",
    riskLevel: "high",
    slos: [
      { metric: "availability", target: "99.95%", current: "99.97%", status: "met" },
      { metric: "latency-p95", target: "< 250ms", current: "212ms", status: "met" },
      { metric: "error-rate", target: "< 0.1%", current: "0.04%", status: "met" },
    ],
    argoAppName: "payments-api-prod",
    errorRate: "0.04%",
    latencyP95: "212ms",
  },
  {
    id: "app-portal",
    name: "Customer Portal",
    slug: "customer-portal",
    description: "Public web portal for account servicing, statements, and support.",
    ownerUserId: "u-tomas",
    teamId: "team-web",
    repositoryId: "repo-portal",
    technology: ["TypeScript", "React", "Node.js", "Container Apps"],
    cloudEnvironment: "Azure — Container Apps",
    currentVersion: "v5.8.0",
    deploymentStatus: "degraded",
    pipelineHealth: "failing",
    securityScore: 61,
    complianceScore: 74,
    lastDeploymentAt: hours(30),
    openVulnerabilities: { critical: 2, high: 4, medium: 11, low: 14 },
    availability: "99.82%",
    riskLevel: "critical",
    slos: [
      { metric: "availability", target: "99.9%", current: "99.82%", status: "breached" },
      { metric: "latency-p95", target: "< 400ms", current: "486ms", status: "at-risk" },
      { metric: "error-rate", target: "< 0.5%", current: "0.61%", status: "breached" },
    ],
    argoAppName: "customer-portal-prod",
    errorRate: "0.61%",
    latencyP95: "486ms",
  },
  {
    id: "app-identity",
    name: "Identity Service",
    slug: "identity-service",
    description: "OIDC token issuance, session management, and step-up authentication.",
    ownerUserId: "u-priya",
    teamId: "team-identity",
    repositoryId: "repo-identity",
    technology: ["C#", ".NET 9", "AKS", "Entra ID"],
    cloudEnvironment: "Azure — AKS (private cluster)",
    currentVersion: "v3.2.1",
    deploymentStatus: "healthy",
    pipelineHealth: "healthy",
    securityScore: 93,
    complianceScore: 96,
    lastDeploymentAt: hours(52),
    openVulnerabilities: { critical: 0, high: 1, medium: 3, low: 6 },
    availability: "99.99%",
    riskLevel: "medium",
    slos: [
      { metric: "availability", target: "99.99%", current: "99.99%", status: "met" },
      { metric: "latency-p95", target: "< 120ms", current: "88ms", status: "met" },
      { metric: "error-rate", target: "< 0.05%", current: "0.01%", status: "met" },
    ],
    argoAppName: "identity-service-prod",
    errorRate: "0.01%",
    latencyP95: "88ms",
  },
  {
    id: "app-notify",
    name: "Notification Worker",
    slug: "notification-worker",
    description: "Async worker for email, SMS, and push notifications via Service Bus.",
    ownerUserId: "u-derek",
    teamId: "team-messaging",
    repositoryId: "repo-notify",
    technology: ["Go", "Service Bus", "Container Apps"],
    cloudEnvironment: "Azure — Container Apps",
    currentVersion: "v1.9.7",
    deploymentStatus: "progressing",
    pipelineHealth: "unstable",
    securityScore: 77,
    complianceScore: 82,
    lastDeploymentAt: hours(2),
    openVulnerabilities: { critical: 0, high: 2, medium: 6, low: 4 },
    availability: "99.91%",
    riskLevel: "medium",
    slos: [
      { metric: "availability", target: "99.9%", current: "99.91%", status: "met" },
      { metric: "latency-p95", target: "< 2s (delivery)", current: "1.4s", status: "met" },
      { metric: "error-rate", target: "< 0.3%", current: "0.22%", status: "at-risk" },
    ],
    argoAppName: "notification-worker-prod",
    errorRate: "0.22%",
    latencyP95: "1.4s",
  },
  {
    id: "app-reporting",
    name: "Reporting Platform",
    slug: "reporting-platform",
    description: "Regulatory and management reporting with nightly batch aggregation.",
    ownerUserId: "u-aiko",
    teamId: "team-data",
    repositoryId: "repo-reporting",
    technology: ["Python", "Spark", "AKS", "Synapse"],
    cloudEnvironment: "Azure — AKS + Synapse",
    currentVersion: "v4.1.0",
    deploymentStatus: "rolled-back",
    pipelineHealth: "unstable",
    securityScore: 69,
    complianceScore: 88,
    lastDeploymentAt: hours(11),
    openVulnerabilities: { critical: 1, high: 3, medium: 8, low: 12 },
    availability: "99.88%",
    riskLevel: "high",
    slos: [
      { metric: "availability", target: "99.9%", current: "99.88%", status: "at-risk" },
      { metric: "latency-p95", target: "< 5s (query)", current: "3.8s", status: "met" },
      { metric: "error-rate", target: "< 1%", current: "0.4%", status: "met" },
    ],
    argoAppName: "reporting-platform-prod",
    errorRate: "0.4%",
    latencyP95: "3.8s",
  },
];

export function applicationById(id: string): Application {
  const app = applications.find((a) => a.id === id);
  if (!app) throw new Error(`Unknown mock application: ${id}`);
  return app;
}

const baseNodes: ArchitectureDiagram["nodes"] = [
  { id: "github", label: "GitHub Repository", kind: "scm", status: "healthy", owner: "Platform Engineering", description: "Source of truth with branch protection and required reviews.", findingsCount: 0, dependencies: [], relatedStageDefinitionIds: ["pr-opened", "checkout"] },
  { id: "actions", label: "GitHub Actions", kind: "ci", status: "healthy", owner: "Platform Engineering", description: "CI pipeline with OIDC federation to Azure — no long-lived secrets.", findingsCount: 0, dependencies: ["github"], relatedStageDefinitionIds: ["lint", "unit-tests", "image-build"] },
  { id: "terraform", label: "Terraform", kind: "iac", status: "warning", owner: "Platform Engineering", description: "Modular IaC with remote state in Azure Storage and state locking.", findingsCount: 2, dependencies: ["actions"], relatedStageDefinitionIds: ["tf-plan", "tf-policy", "tf-apply"] },
  { id: "acr", label: "Azure Container Registry", kind: "registry", status: "healthy", owner: "Platform Engineering", description: "Private registry; images signed with Cosign, scanned by Trivy.", findingsCount: 1, dependencies: ["actions"], relatedStageDefinitionIds: ["publish", "image-scan", "sign"] },
  { id: "aks", label: "Azure Kubernetes Service", kind: "compute", status: "healthy", owner: "SRE", description: "Private AKS cluster; workload identity, network policies enforced.", findingsCount: 2, dependencies: ["acr", "argocd"], relatedStageDefinitionIds: ["deploy-dev", "prod-deploy"] },
  { id: "argocd", label: "Argo CD", kind: "cd", status: "healthy", owner: "Release Engineering", description: "GitOps controller reconciling desired state from environment repos.", findingsCount: 0, dependencies: ["github"], relatedStageDefinitionIds: ["argo-sync"] },
  { id: "keyvault", label: "Azure Key Vault", kind: "secrets", status: "warning", owner: "Security Engineering", description: "Secrets and certificates; access via managed identity only.", findingsCount: 1, dependencies: [], relatedStageDefinitionIds: ["iam-review"] },
  { id: "entra", label: "Microsoft Entra ID", kind: "identity", status: "healthy", owner: "Identity Platform", description: "Workload identities, RBAC assignments, conditional access.", findingsCount: 0, dependencies: [], relatedStageDefinitionIds: ["iam-review"] },
  { id: "prometheus", label: "Prometheus", kind: "observability", status: "healthy", owner: "SRE", description: "Cluster metrics; SLO burn-rate alerts drive automated rollback.", findingsCount: 0, dependencies: ["aks"], relatedStageDefinitionIds: ["post-verify", "auto-rollback"] },
  { id: "grafana", label: "Grafana", kind: "observability", status: "healthy", owner: "SRE", description: "Dashboards for golden signals and release health.", findingsCount: 0, dependencies: ["prometheus"], relatedStageDefinitionIds: ["post-verify"] },
  { id: "azmonitor", label: "Azure Monitor", kind: "observability", status: "healthy", owner: "SRE", description: "Platform metrics, activity logs, alert routing.", findingsCount: 0, dependencies: ["aks"], relatedStageDefinitionIds: ["post-verify"] },
  { id: "loganalytics", label: "Log Analytics", kind: "observability", status: "healthy", owner: "SRE", description: "Centralized logs with 90-day retention and sensitive-data redaction.", findingsCount: 0, dependencies: ["azmonitor"], relatedStageDefinitionIds: [] },
  { id: "appinsights", label: "Application Insights", kind: "observability", status: "healthy", owner: "SRE", description: "Distributed tracing and dependency maps.", findingsCount: 0, dependencies: ["azmonitor"], relatedStageDefinitionIds: ["post-verify"] },
  { id: "azpolicy", label: "Azure Policy", kind: "governance", status: "healthy", owner: "Security Engineering", description: "Deny-by-default guardrails; policy-as-code evaluated in pipeline.", findingsCount: 0, dependencies: [], relatedStageDefinitionIds: ["tf-policy", "iam-review"] },
  { id: "defender", label: "Defender for Cloud", kind: "security", status: "warning", owner: "Security Engineering", description: "CSPM and workload protection; findings feed the command center.", findingsCount: 3, dependencies: [], relatedStageDefinitionIds: ["image-scan"] },
];

const baseEdges: ArchitectureDiagram["edges"] = [
  { id: "e1", source: "github", target: "actions", label: "triggers" },
  { id: "e2", source: "actions", target: "terraform", label: "plan/apply" },
  { id: "e3", source: "actions", target: "acr", label: "push image" },
  { id: "e4", source: "github", target: "argocd", label: "desired state" },
  { id: "e5", source: "argocd", target: "aks", label: "sync" },
  { id: "e6", source: "acr", target: "aks", label: "pull" },
  { id: "e7", source: "entra", target: "aks", label: "workload identity" },
  { id: "e8", source: "keyvault", target: "aks", label: "secrets (CSI)" },
  { id: "e9", source: "aks", target: "prometheus", label: "metrics" },
  { id: "e10", source: "prometheus", target: "grafana", label: "dashboards" },
  { id: "e11", source: "aks", target: "azmonitor", label: "platform logs" },
  { id: "e12", source: "azmonitor", target: "loganalytics", label: "ingest" },
  { id: "e13", source: "azmonitor", target: "appinsights", label: "traces" },
  { id: "e14", source: "azpolicy", target: "aks", label: "guardrails" },
  { id: "e15", source: "defender", target: "aks", label: "protection" },
  { id: "e16", source: "terraform", target: "keyvault", label: "provisions" },
];

export const architectureDiagrams: ArchitectureDiagram[] = applications.map((app) => ({
  id: `arch-${app.id}`,
  applicationId: app.id,
  nodes: baseNodes,
  edges: baseEdges,
}));

export const incidents: Incident[] = [
  {
    id: "inc-401",
    applicationId: "app-portal",
    title: "Elevated 5xx on portal login after v5.8.0",
    severity: "high",
    status: "active",
    startedAt: hours(3),
    summary: "Error rate breached SLO after latest deploy; canary analysis flagged session-service timeouts.",
  },
  {
    id: "inc-398",
    applicationId: "app-reporting",
    title: "Reporting batch overrun — rollback executed",
    severity: "medium",
    status: "mitigated",
    startedAt: hours(12),
    summary: "v4.2.0 introduced a partition regression; automated rollback restored v4.1.0.",
  },
];
