import type { SecurityFinding } from "@secureflow/types";

const now = Date.now();
const daysAgo = (n: number) => new Date(now - n * 86_400_000).toISOString();
const daysAhead = (n: number) => new Date(now + n * 86_400_000).toISOString();

const DISCLAIMER =
  "AI-generated analysis. Requires human review before action; it never bypasses approval gates.";

export const securityFindings: SecurityFinding[] = [
  {
    id: "find-cve-portal",
    title: "Critical CVE-2025-21614 in node:20.11-alpine base image",
    description:
      "libcrypto3 3.3.0-r2 in the base image is vulnerable to a heap overflow reachable via TLS handshake processing. A public PoC exists.",
    applicationId: "app-portal",
    repositoryId: "repo-portal",
    branch: "feature/session-refresh",
    environment: "staging",
    scanner: "trivy",
    type: "container",
    severity: "critical",
    status: "open",
    ruleId: "TRIVY-CVE-2025-21614",
    cve: "CVE-2025-21614",
    affectedResource: "acrmeridianprod.azurecr.io/customer-portal:v5.9.0-beta.1",
    filePath: "docker/Dockerfile.web",
    lineNumber: 1,
    exploitability: "high",
    reachability: "reachable",
    businessImpact: "Remote code execution on internet-facing portal pods; direct customer-data exposure path.",
    suggestedFix: "Rebuild on node:20.19-alpine3.21 (patched libcrypto3 3.3.2-r4); pin base image by digest.",
    aiExplanation:
      "The vulnerable OpenSSL function is invoked during inbound TLS session resumption, which this workload performs at the ingress sidecar. Exploitability is high because the portal terminates TLS from untrusted clients. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "owasp-top-10", controlId: "A06" },
      { frameworkId: "pci-dss", controlId: "6.3.3" },
      { frameworkId: "azure-security-benchmark", controlId: "PV-6" },
    ],
    evidence: ["trivy-report-run-2210.json", "sbom-run-2210.spdx.json"],
    suppressionHistory: [],
    ownerUserId: "u-tomas",
    slaDueDate: daysAhead(2),
    firstDetectedAt: daysAgo(1),
    pipelineRunId: "run-2210",
    blocksDeployment: true,
  },
  {
    id: "find-root-container",
    title: "Portal container runs as root user",
    description: "The customer-portal image does not declare USER; Kubernetes admission allows it via legacy exemption.",
    applicationId: "app-portal",
    repositoryId: "repo-portal",
    branch: "feature/session-refresh",
    environment: "staging",
    scanner: "trivy",
    type: "container",
    severity: "high",
    status: "in-remediation",
    ruleId: "KSV-012",
    affectedResource: "deployment/customer-portal, container 'web'",
    filePath: "docker/Dockerfile.web",
    lineNumber: 24,
    exploitability: "medium",
    reachability: "reachable",
    businessImpact: "Container escape blast radius includes node-level credentials.",
    suggestedFix: "Add non-root user (USER 10001), set runAsNonRoot: true and drop ALL capabilities in the pod securityContext.",
    aiExplanation: "Running as UID 0 turns any code-execution bug into a node-compromise candidate. The fix is low-effort and has no runtime impact for this workload. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "cis-benchmarks", controlId: "5.2.6" },
      { frameworkId: "nist-csf", controlId: "PR.PS-01" },
    ],
    evidence: ["trivy-report-run-2210.json"],
    suppressionHistory: [],
    ownerUserId: "u-tomas",
    slaDueDate: daysAhead(9),
    firstDetectedAt: daysAgo(4),
    pipelineRunId: "run-2210",
    blocksDeployment: false,
  },
  {
    id: "find-secret-notify",
    title: "Hardcoded Twilio auth token in test fixture",
    description: "Gitleaks matched a live-format Twilio token in notification-worker test fixtures committed 3 weeks ago.",
    applicationId: "app-notify",
    repositoryId: "repo-notify",
    branch: "main",
    environment: "development",
    scanner: "gitleaks",
    type: "secret",
    severity: "high",
    status: "in-remediation",
    ruleId: "twilio-api-key",
    affectedResource: "tests/fixtures/sms-callback.json",
    filePath: "tests/fixtures/sms-callback.json",
    lineNumber: 17,
    exploitability: "high",
    reachability: "unknown",
    businessImpact: "If the token is live, an attacker can send SMS as the bank — phishing and fraud vector.",
    suggestedFix: "Rotate the token in Twilio, purge from git history (git filter-repo), replace fixture with an obvious dummy value, add pre-commit gitleaks hook.",
    aiExplanation: "Token entropy and prefix match Twilio's production format. History rewrite is required because the token remains in reachable commits even after deletion. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "owasp-top-10", controlId: "A07" },
      { frameworkId: "soc-2", controlId: "CC6.1" },
      { frameworkId: "iso-27001", controlId: "A.8.24" },
    ],
    evidence: ["gitleaks-report-run-0509.json"],
    suppressionHistory: [],
    ownerUserId: "u-derek",
    slaDueDate: daysAhead(1),
    firstDetectedAt: daysAgo(6),
    blocksDeployment: true,
  },
  {
    id: "find-dep-axios",
    title: "Outdated dependency: axios 1.6.2 (SSRF bypass)",
    description: "payments-api pins axios 1.6.2 which is vulnerable to CVE-2024-28849 redirect-based credential leakage.",
    applicationId: "app-payments",
    repositoryId: "repo-payments",
    branch: "release/2.15",
    environment: "staging",
    scanner: "snyk",
    type: "dependency",
    severity: "medium",
    status: "open",
    ruleId: "SNYK-JS-AXIOS-6144788",
    cve: "CVE-2024-28849",
    affectedResource: "package.json > axios@1.6.2",
    filePath: "package.json",
    lineNumber: 34,
    exploitability: "medium",
    reachability: "reachable",
    businessImpact: "Outbound webhook calls could leak Authorization headers on cross-origin redirects.",
    suggestedFix: "Upgrade to axios >= 1.8.0 and set maxRedirects: 0 on the webhook client.",
    aiExplanation: "The vulnerable code path executes in the partner-webhook dispatcher, which follows redirects by default. Upgrading plus disabling redirects removes both the CVE and the class of issue. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "owasp-top-10", controlId: "A06" },
      { frameworkId: "pci-dss", controlId: "6.3.3" },
    ],
    evidence: ["snyk-report-run-1482.json"],
    suppressionHistory: [],
    ownerUserId: "u-rowan",
    slaDueDate: daysAhead(18),
    firstDetectedAt: daysAgo(2),
    pipelineRunId: "run-1482",
    blocksDeployment: false,
  },
  {
    id: "find-storage-public",
    title: "Reporting evidence storage account allows public blob access",
    description: "Defender for Cloud flags stmeridianreports with allowBlobPublicAccess=true; one container is 'blob' level public.",
    applicationId: "app-reporting",
    repositoryId: "repo-reporting",
    branch: "main",
    environment: "production",
    scanner: "defender-for-cloud",
    type: "misconfiguration",
    severity: "critical",
    status: "open",
    ruleId: "ASB-DP-4",
    affectedResource: "stmeridianreports (westeurope)",
    exploitability: "high",
    reachability: "reachable",
    businessImpact: "Regulatory report drafts could be enumerated anonymously — reportable data exposure.",
    suggestedFix: "Set allow_blob_public_access = false in the storage module, front downloads with SAS via the reporting API, enable private endpoint.",
    aiExplanation: "Anonymous enumeration was observed in access logs from two unknown ASNs in the last 72h (listing only, no confirmed downloads). Treat as active exposure. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "azure-security-benchmark", controlId: "DP-4" },
      { frameworkId: "iso-27001", controlId: "A.8.12" },
      { frameworkId: "soc-2", controlId: "CC6.6" },
    ],
    evidence: ["defender-alert-88213.json", "storage-access-log-extract.csv"],
    suppressionHistory: [],
    ownerUserId: "u-aiko",
    slaDueDate: daysAhead(0.5),
    firstDetectedAt: daysAgo(2),
    blocksDeployment: true,
  },
  {
    id: "find-iam-wide",
    title: "Overly permissive role: Contributor at subscription scope for CI identity",
    description: "The GitHub OIDC service principal for reporting-platform holds Contributor on the whole subscription instead of scoped resource groups.",
    applicationId: "app-reporting",
    repositoryId: "repo-reporting",
    branch: "main",
    environment: "production",
    scanner: "defender-for-cloud",
    type: "iam",
    severity: "high",
    status: "open",
    ruleId: "ASB-PA-7",
    affectedResource: "sp-gh-reporting-deploy (Entra app 5f3c…)",
    exploitability: "medium",
    reachability: "reachable",
    businessImpact: "A compromised workflow could modify unrelated production resources subscription-wide.",
    suggestedFix: "Replace with least-privilege custom role scoped to rg-reporting-{env}; separate plan (Reader) and apply identities.",
    aiExplanation: "Blast-radius analysis: this principal can alter 214 resources outside its own application's resource groups. Scoping reduces that to 31. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "azure-security-benchmark", controlId: "PA-7" },
      { frameworkId: "nist-csf", controlId: "PR.AA-05" },
      { frameworkId: "iso-27001", controlId: "A.8.2" },
    ],
    evidence: ["entra-role-assignments-export.json"],
    suppressionHistory: [],
    ownerUserId: "u-marcus",
    slaDueDate: daysAhead(6),
    firstDetectedAt: daysAgo(9),
    blocksDeployment: false,
  },
  {
    id: "find-sg-open",
    title: "Terraform NSG rule opens 0.0.0.0/0 on port 5432",
    description: "A convenience rule in the reporting data subnet allows PostgreSQL from any source.",
    applicationId: "app-reporting",
    repositoryId: "repo-reporting",
    branch: "infra/synapse-peering",
    environment: "development",
    scanner: "tfsec",
    type: "iac",
    severity: "high",
    status: "open",
    ruleId: "azure-network-no-public-ingress",
    affectedResource: "module.network.azurerm_network_security_rule.pg_debug",
    filePath: "infrastructure/modules/network/main.tf",
    lineNumber: 88,
    exploitability: "high",
    reachability: "not-reachable",
    businessImpact: "Currently unreachable (private subnet), but one route-table change away from database exposure.",
    suggestedFix: "Delete the debug rule; use Azure Bastion + JIT access for troubleshooting sessions.",
    aiExplanation: "Defense-in-depth violation: the rule is dormant only because of current routing. Reachability could silently flip during the planned Synapse peering work. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "cis-benchmarks", controlId: "6.2" },
      { frameworkId: "azure-security-benchmark", controlId: "NS-1" },
    ],
    evidence: ["tfsec-report-run-0711.json"],
    suppressionHistory: [],
    ownerUserId: "u-marcus",
    slaDueDate: daysAhead(11),
    firstDetectedAt: daysAgo(5),
    blocksDeployment: false,
  },
  {
    id: "find-kv-public",
    title: "Azure Key Vault public network access enabled",
    description: "Checkov blocked a change setting identity Key Vault network ACL default action to Allow.",
    applicationId: "app-identity",
    repositoryId: "repo-identity",
    branch: "infra/kv-firewall",
    environment: "development",
    scanner: "checkov",
    type: "iac",
    severity: "high",
    status: "open",
    ruleId: "CKV_AZURE_109",
    affectedResource: "module.identity_kv.azurerm_key_vault.main",
    filePath: "infrastructure/modules/key-vault/main.tf",
    lineNumber: 41,
    exploitability: "medium",
    reachability: "not-reachable",
    businessImpact: "Signing keys for OIDC tokens would become reachable from the public internet (auth still required).",
    suggestedFix: "Keep default_action = \"Deny\"; add the build-agent subnet to the allow list or use a self-hosted runner inside the VNet.",
    aiExplanation: "The change was proposed to unblock CI, but the correct fix is network-scoped allowance, not public exposure of the vault that anchors all token trust. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "azure-security-benchmark", controlId: "NS-2" },
      { frameworkId: "iso-27001", controlId: "A.8.20" },
    ],
    evidence: ["checkov-report-run-0862.json"],
    suppressionHistory: [],
    ownerUserId: "u-priya",
    slaDueDate: daysAhead(13),
    firstDetectedAt: daysAgo(5),
    pipelineRunId: "run-0862",
    blocksDeployment: true,
  },
  {
    id: "find-missing-encryption",
    title: "Notification queue payloads stored without customer-managed encryption",
    description: "Service Bus namespace uses Microsoft-managed keys; policy requires CMK for PII-bearing queues.",
    applicationId: "app-notify",
    repositoryId: "repo-notify",
    branch: "main",
    environment: "production",
    scanner: "checkov",
    type: "misconfiguration",
    severity: "medium",
    status: "accepted-risk",
    ruleId: "CKV_AZURE_199",
    affectedResource: "sb-meridian-notify-prod",
    exploitability: "low",
    reachability: "not-reachable",
    businessImpact: "Contractual (not technical) gap: enterprise policy mandates CMK for PII at rest.",
    suggestedFix: "Provision a Key Vault key with rotation policy and enable customer_managed_key on the namespace.",
    aiExplanation: "Risk acceptance is reasonable short-term: data is TLS-in-transit and MS-managed-key at rest. The exception should not be renewed past the platform's CMK rollout in Q3. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "iso-27001", controlId: "A.8.24" },
      { frameworkId: "soc-2", controlId: "CC6.7" },
    ],
    evidence: ["risk-exception-rex-31.pdf"],
    suppressionHistory: [
      { date: daysAgo(20), by: "Derek Mensah", reason: "Accepted until CMK platform rollout (REX-31), expires in 45 days." },
    ],
    ownerUserId: "u-derek",
    slaDueDate: daysAhead(45),
    firstDetectedAt: daysAgo(34),
    blocksDeployment: false,
  },
  {
    id: "find-unsigned-image",
    title: "Unsigned container image deployed to development",
    description: "reporting-platform dev environment runs an image without a Cosign signature (emergency hotfix path bypassed signing).",
    applicationId: "app-reporting",
    repositoryId: "repo-reporting",
    branch: "hotfix/csv-escape",
    environment: "development",
    scanner: "cosign",
    type: "container",
    severity: "medium",
    status: "resolved",
    ruleId: "COSIGN-VERIFY-FAIL",
    affectedResource: "acrmeridianprod.azurecr.io/reporting-platform:v4.1.1-hotfix",
    exploitability: "low",
    reachability: "unknown",
    businessImpact: "Supply-chain provenance gap; cannot attest build integrity for the hotfix.",
    suggestedFix: "Re-run the standard pipeline for the hotfix; enforce signature verification in the dev admission policy (currently prod/staging only).",
    aiExplanation: "The bypass used the documented break-glass flow, but dev admission should still verify signatures to keep parity with prod. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "nist-csf", controlId: "PR.PS-06" },
      { frameworkId: "azure-security-benchmark", controlId: "PV-2" },
    ],
    evidence: ["cosign-verify-log.txt", "break-glass-ticket-BG-77.json"],
    suppressionHistory: [],
    ownerUserId: "u-aiko",
    slaDueDate: daysAgo(1),
    firstDetectedAt: daysAgo(8),
    blocksDeployment: false,
  },
  {
    id: "find-missing-sbom",
    title: "Missing SBOM for legacy batch image",
    description: "reporting-legacy-batch:2019.3 predates SBOM generation; no dependency inventory exists.",
    applicationId: "app-reporting",
    repositoryId: "repo-reporting",
    branch: "main",
    environment: "production",
    scanner: "syft",
    type: "container",
    severity: "low",
    status: "open",
    ruleId: "SBOM-MISSING",
    affectedResource: "acrmeridianprod.azurecr.io/reporting-legacy-batch:2019.3",
    exploitability: "unknown",
    reachability: "unknown",
    businessImpact: "Cannot answer 'are we affected?' for new CVEs in this image; slows incident response.",
    suggestedFix: "Generate SBOM with syft against the running image and store in the evidence bucket; schedule image modernization.",
    aiExplanation: "This image runs monthly with narrow network access, so risk is bounded — but the SBOM gap makes every future CVE triage manual. " + DISCLAIMER,
    complianceMappings: [{ frameworkId: "nist-csf", controlId: "ID.AM-02" }],
    evidence: [],
    suppressionHistory: [],
    ownerUserId: "u-aiko",
    slaDueDate: daysAhead(40),
    firstDetectedAt: daysAgo(15),
    blocksDeployment: false,
  },
  {
    id: "find-dast-auth",
    title: "DAST: password reset flow lacks rate limiting",
    description: "OWASP ZAP active scan sustained 300 reset requests/min without throttling or lockout on staging portal.",
    applicationId: "app-portal",
    repositoryId: "repo-portal",
    branch: "main",
    environment: "staging",
    scanner: "owasp-zap",
    type: "dast",
    severity: "high",
    status: "open",
    ruleId: "ZAP-10202",
    affectedResource: "POST /api/v2/auth/password-reset",
    exploitability: "high",
    reachability: "reachable",
    businessImpact: "Enables user enumeration and email-bombing of customers; precursors to account takeover.",
    suggestedFix: "Add per-account and per-IP rate limits (5/hr) with exponential backoff; return uniform responses regardless of account existence.",
    aiExplanation: "Response-time analysis also distinguishes existing vs non-existing accounts (~180ms delta), so uniform-response handling matters as much as throttling. " + DISCLAIMER,
    complianceMappings: [
      { frameworkId: "owasp-top-10", controlId: "A07" },
      { frameworkId: "pci-dss", controlId: "8.3.4" },
    ],
    evidence: ["zap-scan-run-2208.html"],
    suppressionHistory: [],
    ownerUserId: "u-tomas",
    slaDueDate: daysAhead(7),
    firstDetectedAt: daysAgo(3),
    blocksDeployment: false,
  },
  {
    id: "find-missing-limits",
    title: "Kubernetes: notification-worker containers missing resource limits",
    description: "Deployment spec omits CPU/memory limits; a runaway template render can starve co-located workloads.",
    applicationId: "app-notify",
    repositoryId: "repo-notify",
    branch: "main",
    environment: "production",
    scanner: "kube-bench",
    type: "misconfiguration",
    severity: "medium",
    status: "in-remediation",
    ruleId: "KSV-011",
    affectedResource: "deployment/notification-worker",
    filePath: "deploy/base/deployment.yaml",
    lineNumber: 42,
    exploitability: "low",
    reachability: "reachable",
    businessImpact: "Noisy-neighbor risk on shared node pool; availability, not confidentiality.",
    suggestedFix: "Set requests cpu=100m/mem=256Mi, limits cpu=500m/mem=512Mi based on P99 usage; add LimitRange to the namespace.",
    aiExplanation: "30-day P99 usage is 210m CPU / 340Mi memory; the suggested limits leave 2x headroom without allowing node starvation. " + DISCLAIMER,
    complianceMappings: [{ frameworkId: "cis-benchmarks", controlId: "5.4.1" }],
    evidence: ["kube-bench-report-week29.json"],
    suppressionHistory: [],
    ownerUserId: "u-derek",
    slaDueDate: daysAhead(21),
    firstDetectedAt: daysAgo(12),
    blocksDeployment: false,
  },
  {
    id: "find-sast-sqli",
    title: "SAST: string-built SQL in statement search",
    description: "SonarQube flags concatenated SQL with user input in the portal statement-search endpoint (S3649).",
    applicationId: "app-portal",
    repositoryId: "repo-portal",
    branch: "main",
    environment: "production",
    scanner: "sonarqube",
    type: "code-quality",
    severity: "high",
    status: "false-positive",
    ruleId: "S3649",
    affectedResource: "src/statements/search.ts",
    filePath: "src/statements/search.ts",
    lineNumber: 204,
    exploitability: "low",
    reachability: "not-reachable",
    businessImpact: "None if confirmed FP: input passes through an allow-list mapper before concatenation.",
    suggestedFix: "Refactor to parameterized query anyway to remove the taint pattern and the recurring alert.",
    aiExplanation: "Marked false-positive after manual review: the concatenated value is drawn from a fixed enum map, not raw input. The refactor is still worthwhile to silence the detector. " + DISCLAIMER,
    complianceMappings: [{ frameworkId: "owasp-top-10", controlId: "A03" }],
    evidence: ["sonarqube-review-note-8841.md"],
    suppressionHistory: [
      { date: daysAgo(10), by: "Priya Natarajan", reason: "Confirmed FP — enum-mapped value; refactor tracked as REM-3098." },
    ],
    ownerUserId: "u-tomas",
    slaDueDate: daysAhead(30),
    firstDetectedAt: daysAgo(14),
    blocksDeployment: false,
  },
];
